import { ImageSourcePropType } from 'react-native';

const localImageMap: Record<string, ImageSourcePropType> = {
  'assets/pose-collection/blurred/001-street-walk-candid.jpg': require('../../../assets/pose-collection/blurred/001-street-walk-candid.jpg'),
  'assets/pose-collection/blurred/002-crosswalk-pause.jpg': require('../../../assets/pose-collection/blurred/002-crosswalk-pause.jpg'),
  'assets/pose-collection/blurred/003-wall-lean-relax.jpg': require('../../../assets/pose-collection/blurred/003-wall-lean-relax.jpg'),
  'assets/pose-collection/blurred/004-stair-sit-portrait.jpg': require('../../../assets/pose-collection/blurred/004-stair-sit-portrait.jpg'),
  'assets/pose-collection/blurred/005-railway-handrail-lookback.jpg': require('../../../assets/pose-collection/blurred/005-railway-handrail-lookback.jpg'),
  'assets/pose-collection/blurred/006-phone-check-natural.jpg': require('../../../assets/pose-collection/blurred/006-phone-check-natural.jpg'),
  'assets/pose-collection/blurred/007-coffee-cup-side-profile.jpg': require('../../../assets/pose-collection/blurred/007-coffee-cup-side-profile.jpg'),
  'assets/pose-collection/blurred/008-table-elbow-rest.jpg': require('../../../assets/pose-collection/blurred/008-table-elbow-rest.jpg'),
  'assets/pose-collection/blurred/009-window-light-soft-smile.jpg': require('../../../assets/pose-collection/blurred/009-window-light-soft-smile.jpg'),
  'assets/pose-collection/blurred/010-mirror-selfie-minimal.jpg': require('../../../assets/pose-collection/blurred/010-mirror-selfie-minimal.jpg'),
  'assets/pose-collection/blurred/011-mirror-full-body-fit-check.jpg': require('../../../assets/pose-collection/blurred/011-mirror-full-body-fit-check.jpg'),
  'assets/pose-collection/blurred/012-hallway-runway.jpg': require('../../../assets/pose-collection/blurred/012-hallway-runway.jpg'),
  'assets/pose-collection/blurred/013-neon-night-stand.jpg': require('../../../assets/pose-collection/blurred/013-neon-night-stand.jpg'),
  'assets/pose-collection/blurred/014-neon-backlight-silhouette.jpg': require('../../../assets/pose-collection/blurred/014-neon-backlight-silhouette.jpg'),
  'assets/pose-collection/blurred/015-street-lamp-spin.jpg': require('../../../assets/pose-collection/blurred/015-street-lamp-spin.jpg'),
  'assets/pose-collection/blurred/016-rooftop-skyline-back.jpg': require('../../../assets/pose-collection/blurred/016-rooftop-skyline-back.jpg'),
  'assets/pose-collection/blurred/017-rooftop-sit-edge-safe.jpg': require('../../../assets/pose-collection/blurred/017-rooftop-sit-edge-safe.jpg'),
  'assets/pose-collection/blurred/018-park-bench-relax.jpg': require('../../../assets/pose-collection/blurred/018-park-bench-relax.jpg'),
  'assets/pose-collection/blurred/019-grass-lie-down-sky.jpg': require('../../../assets/pose-collection/blurred/019-grass-lie-down-sky.jpg'),
  'assets/pose-collection/blurred/020-tree-shadow-portrait.jpg': require('../../../assets/pose-collection/blurred/020-tree-shadow-portrait.jpg'),
  'assets/pose-collection/blurred/021-beach-walk-barefoot.jpg': require('../../../assets/pose-collection/blurred/021-beach-walk-barefoot.jpg'),
  'assets/pose-collection/blurred/022-beach-back-to-camera.jpg': require('../../../assets/pose-collection/blurred/022-beach-back-to-camera.jpg'),
  'assets/pose-collection/blurred/023-sea-wall-sit.jpg': require('../../../assets/pose-collection/blurred/023-sea-wall-sit.jpg'),
  'assets/pose-collection/blurred/024-couple-hand-in-hand-walk.jpg': require('../../../assets/pose-collection/blurred/024-couple-hand-in-hand-walk.jpg'),
  'assets/pose-collection/blurred/025-couple-forehead-touch.jpg': require('../../../assets/pose-collection/blurred/025-couple-forehead-touch.jpg'),
  'assets/pose-collection/blurred/026-couple-back-hug.jpg': require('../../../assets/pose-collection/blurred/026-couple-back-hug.jpg'),
  'assets/pose-collection/blurred/027-friend-group-jump.jpg': require('../../../assets/pose-collection/blurred/027-friend-group-jump.jpg'),
  'assets/pose-collection/blurred/028-friend-group-triangle.jpg': require('../../../assets/pose-collection/blurred/028-friend-group-triangle.jpg'),
  'assets/pose-collection/blurred/029-friend-group-sitting-curb.jpg': require('../../../assets/pose-collection/blurred/029-friend-group-sitting-curb.jpg'),
  'assets/pose-collection/blurred/030-graduation-cap-toss.jpg': require('../../../assets/pose-collection/blurred/030-graduation-cap-toss.jpg'),
  'assets/pose-collection/blurred/031-campus-stair-walk.jpg': require('../../../assets/pose-collection/blurred/031-campus-stair-walk.jpg'),
  'assets/pose-collection/blurred/032-library-book-peek.jpg': require('../../../assets/pose-collection/blurred/032-library-book-peek.jpg'),
  'assets/pose-collection/blurred/033-scooter-side-stand.jpg': require('../../../assets/pose-collection/blurred/033-scooter-side-stand.jpg'),
  'assets/pose-collection/blurred/034-bike-ride-push.jpg': require('../../../assets/pose-collection/blurred/034-bike-ride-push.jpg'),
  'assets/pose-collection/blurred/035-car-window-mood.jpg': require('../../../assets/pose-collection/blurred/035-car-window-mood.jpg'),
  'assets/pose-collection/blurred/036-rain-umbrella-walk.jpg': require('../../../assets/pose-collection/blurred/036-rain-umbrella-walk.jpg'),
  'assets/pose-collection/blurred/037-umbrella-backlight-neon.jpg': require('../../../assets/pose-collection/blurred/037-umbrella-backlight-neon.jpg'),
  'assets/pose-collection/blurred/038-bridge-rail-centered.jpg': require('../../../assets/pose-collection/blurred/038-bridge-rail-centered.jpg'),
  'assets/pose-collection/blurred/039-tunnel-perspective-walk.jpg': require('../../../assets/pose-collection/blurred/039-tunnel-perspective-walk.jpg'),
  'assets/pose-collection/blurred/040-skateboard-sit-cool.jpg': require('../../../assets/pose-collection/blurred/040-skateboard-sit-cool.jpg'),
  'assets/pose-collection/blurred/041-skate-push-motion.jpg': require('../../../assets/pose-collection/blurred/041-skate-push-motion.jpg'),
  'assets/pose-collection/blurred/042-basket-court-casual.jpg': require('../../../assets/pose-collection/blurred/042-basket-court-casual.jpg'),
  'assets/pose-collection/blurred/043-headphones-street-vibe.jpg': require('../../../assets/pose-collection/blurred/043-headphones-street-vibe.jpg'),
  'assets/pose-collection/blurred/044-bookstore-aisle-browse.jpg': require('../../../assets/pose-collection/blurred/044-bookstore-aisle-browse.jpg'),
  'assets/pose-collection/blurred/045-record-store-flip.jpg': require('../../../assets/pose-collection/blurred/045-record-store-flip.jpg'),
  'assets/pose-collection/blurred/046-arcade-neon-play.jpg': require('../../../assets/pose-collection/blurred/046-arcade-neon-play.jpg'),
  'assets/pose-collection/blurred/047-food-court-tray-walk.jpg': require('../../../assets/pose-collection/blurred/047-food-court-tray-walk.jpg'),
  'assets/pose-collection/blurred/048-festival-crowd-glow.jpg': require('../../../assets/pose-collection/blurred/048-festival-crowd-glow.jpg'),
  'assets/pose-collection/blurred/049-polaroid-cover-face.jpg': require('../../../assets/pose-collection/blurred/049-polaroid-cover-face.jpg'),
  'assets/pose-collection/blurred/050-sunset-over-shoulder.jpg': require('../../../assets/pose-collection/blurred/050-sunset-over-shoulder.jpg'),
  'assets/pose-collection/blurred/051-golden-hour-hair-flip.jpg': require('../../../assets/pose-collection/blurred/051-golden-hour-hair-flip.jpg'),
  'assets/pose-collection/blurred/052-shadow-line-face.jpg': require('../../../assets/pose-collection/blurred/052-shadow-line-face.jpg'),
  'assets/pose-collection/blurred/053-street-frame-01.jpg': require('../../../assets/pose-collection/blurred/053-street-frame-01.jpg'),
  'assets/pose-collection/blurred/054-street-frame-02.jpg': require('../../../assets/pose-collection/blurred/054-street-frame-02.jpg'),
  'assets/pose-collection/blurred/055-street-frame-03.jpg': require('../../../assets/pose-collection/blurred/055-street-frame-03.jpg'),
  'assets/pose-collection/blurred/056-street-frame-04.jpg': require('../../../assets/pose-collection/blurred/056-street-frame-04.jpg'),
  'assets/pose-collection/blurred/057-street-frame-05.jpg': require('../../../assets/pose-collection/blurred/057-street-frame-05.jpg'),
  'assets/pose-collection/blurred/058-street-frame-06.jpg': require('../../../assets/pose-collection/blurred/058-street-frame-06.jpg'),
  'assets/pose-collection/blurred/059-street-frame-07.jpg': require('../../../assets/pose-collection/blurred/059-street-frame-07.jpg'),
  'assets/pose-collection/blurred/060-street-frame-08.jpg': require('../../../assets/pose-collection/blurred/060-street-frame-08.jpg'),
  'assets/pose-collection/blurred/061-street-frame-09.jpg': require('../../../assets/pose-collection/blurred/061-street-frame-09.jpg'),
  'assets/pose-collection/blurred/062-street-frame-10.jpg': require('../../../assets/pose-collection/blurred/062-street-frame-10.jpg'),
  'assets/pose-collection/blurred/063-street-frame-11.jpg': require('../../../assets/pose-collection/blurred/063-street-frame-11.jpg'),
  'assets/pose-collection/blurred/064-street-frame-12.jpg': require('../../../assets/pose-collection/blurred/064-street-frame-12.jpg'),
  'assets/pose-collection/blurred/065-street-frame-13.jpg': require('../../../assets/pose-collection/blurred/065-street-frame-13.jpg'),
  'assets/pose-collection/blurred/066-street-frame-14.jpg': require('../../../assets/pose-collection/blurred/066-street-frame-14.jpg'),
  'assets/pose-collection/blurred/067-street-frame-15.jpg': require('../../../assets/pose-collection/blurred/067-street-frame-15.jpg'),
  'assets/pose-collection/blurred/068-street-frame-16.jpg': require('../../../assets/pose-collection/blurred/068-street-frame-16.jpg'),
  'assets/pose-collection/blurred/069-street-frame-17.jpg': require('../../../assets/pose-collection/blurred/069-street-frame-17.jpg'),
  'assets/pose-collection/blurred/070-street-frame-18.jpg': require('../../../assets/pose-collection/blurred/070-street-frame-18.jpg'),
  'assets/pose-collection/blurred/071-street-frame-19.jpg': require('../../../assets/pose-collection/blurred/071-street-frame-19.jpg'),
  'assets/pose-collection/blurred/072-street-frame-20.jpg': require('../../../assets/pose-collection/blurred/072-street-frame-20.jpg'),
  'assets/pose-collection/blurred/073-coffee-mood-01.jpg': require('../../../assets/pose-collection/blurred/073-coffee-mood-01.jpg'),
  'assets/pose-collection/blurred/074-coffee-mood-02.jpg': require('../../../assets/pose-collection/blurred/074-coffee-mood-02.jpg'),
  'assets/pose-collection/blurred/075-coffee-mood-03.jpg': require('../../../assets/pose-collection/blurred/075-coffee-mood-03.jpg'),
  'assets/pose-collection/blurred/076-coffee-mood-04.jpg': require('../../../assets/pose-collection/blurred/076-coffee-mood-04.jpg'),
  'assets/pose-collection/blurred/077-coffee-mood-05.jpg': require('../../../assets/pose-collection/blurred/077-coffee-mood-05.jpg'),
  'assets/pose-collection/blurred/078-coffee-mood-06.jpg': require('../../../assets/pose-collection/blurred/078-coffee-mood-06.jpg'),
  'assets/pose-collection/blurred/079-coffee-mood-07.jpg': require('../../../assets/pose-collection/blurred/079-coffee-mood-07.jpg'),
  'assets/pose-collection/blurred/080-coffee-mood-08.jpg': require('../../../assets/pose-collection/blurred/080-coffee-mood-08.jpg'),
  'assets/pose-collection/blurred/081-coffee-mood-09.jpg': require('../../../assets/pose-collection/blurred/081-coffee-mood-09.jpg'),
  'assets/pose-collection/blurred/082-coffee-mood-10.jpg': require('../../../assets/pose-collection/blurred/082-coffee-mood-10.jpg'),
  'assets/pose-collection/blurred/083-coffee-mood-11.jpg': require('../../../assets/pose-collection/blurred/083-coffee-mood-11.jpg'),
  'assets/pose-collection/blurred/084-coffee-mood-12.jpg': require('../../../assets/pose-collection/blurred/084-coffee-mood-12.jpg'),
  'assets/pose-collection/blurred/085-coffee-mood-13.jpg': require('../../../assets/pose-collection/blurred/085-coffee-mood-13.jpg'),
  'assets/pose-collection/blurred/086-coffee-mood-14.jpg': require('../../../assets/pose-collection/blurred/086-coffee-mood-14.jpg'),
  'assets/pose-collection/blurred/087-coffee-mood-15.jpg': require('../../../assets/pose-collection/blurred/087-coffee-mood-15.jpg'),
  'assets/pose-collection/blurred/088-scenic-shot-01.jpg': require('../../../assets/pose-collection/blurred/088-scenic-shot-01.jpg'),
  'assets/pose-collection/blurred/089-scenic-shot-02.jpg': require('../../../assets/pose-collection/blurred/089-scenic-shot-02.jpg'),
  'assets/pose-collection/blurred/090-scenic-shot-03.jpg': require('../../../assets/pose-collection/blurred/090-scenic-shot-03.jpg'),
  'assets/pose-collection/blurred/091-scenic-shot-04.jpg': require('../../../assets/pose-collection/blurred/091-scenic-shot-04.jpg'),
  'assets/pose-collection/blurred/092-scenic-shot-05.jpg': require('../../../assets/pose-collection/blurred/092-scenic-shot-05.jpg'),
  'assets/pose-collection/blurred/093-scenic-shot-06.jpg': require('../../../assets/pose-collection/blurred/093-scenic-shot-06.jpg'),
  'assets/pose-collection/blurred/094-scenic-shot-07.jpg': require('../../../assets/pose-collection/blurred/094-scenic-shot-07.jpg'),
  'assets/pose-collection/blurred/095-scenic-shot-08.jpg': require('../../../assets/pose-collection/blurred/095-scenic-shot-08.jpg'),
  'assets/pose-collection/blurred/096-scenic-shot-09.jpg': require('../../../assets/pose-collection/blurred/096-scenic-shot-09.jpg'),
  'assets/pose-collection/blurred/097-scenic-shot-10.jpg': require('../../../assets/pose-collection/blurred/097-scenic-shot-10.jpg'),
  'assets/pose-collection/blurred/098-scenic-shot-11.jpg': require('../../../assets/pose-collection/blurred/098-scenic-shot-11.jpg'),
  'assets/pose-collection/blurred/099-scenic-shot-12.jpg': require('../../../assets/pose-collection/blurred/099-scenic-shot-12.jpg'),
  'assets/pose-collection/blurred/100-scenic-shot-13.jpg': require('../../../assets/pose-collection/blurred/100-scenic-shot-13.jpg'),
  'assets/pose-collection/blurred/101-scenic-shot-14.jpg': require('../../../assets/pose-collection/blurred/101-scenic-shot-14.jpg'),
  'assets/pose-collection/blurred/102-scenic-shot-15.jpg': require('../../../assets/pose-collection/blurred/102-scenic-shot-15.jpg'),
};

export function resolvePoseImageSource(sampleImageUrl: string): ImageSourcePropType {
  if (sampleImageUrl.startsWith('http://') || sampleImageUrl.startsWith('https://')) {
    return { uri: sampleImageUrl };
  }
  return localImageMap[sampleImageUrl] ?? { uri: sampleImageUrl };
}
